### ISSUE TITLE
coinhive.min.js is 404 on the demo site

### ISSUE THREAD

**Issue by exoego** [renyamizuno/point-hive#4]
As of 2018-06-13 09:38 JST, both development version and minified version of the coinhive  is 404 on the demo site.
So the site does not drain CPU of my PC, despite my expectation.

* https://renyamizuno.github.io/point-hive/coinhive.js
* https://renyamizuno.github.io/point-hive/coinhive.min.js

# Steps to reproduce
1. Go to https://renyamizuno.github.io/point-hive/example/index.html
2. Open the developer console from browser's menu or F12 shortcut key.
3. See `ReferenceError: Coinhive is not defined`  shown in console.

# Environment

* OS: Windows 10 64bit
* Browsers
    * Chrome 67.0.3396.79
    * Firefox 60.0.2

**Comment by athos** [comment]
I've run into the same issue with Chrome on my Mac. It's doing "なにもしないよ" literally.

**Comment by renyamizuno** [comment]
> It's doing "なにもしないよ" literally.

Exactly~.
